### PR TITLE
removed connect-master service build section from docker-compose.yml

### PR DESCRIPTION
**Pull request by sndp2693**
Fixes: https://issues.apache.org/jira/browse/STREAMPIPES-336

### CODE REVIEW

**Comment by wipatrick** [comment]
Hi @sndp2693 thanks for fixing this - I'd be happy to merge.

**Comment by sndp2693** [comment]
Sorry i somehow missed it. I have updated the commit message with jira# reference

**Comment by wipatrick** [comment]
No worries and thanks for the fast reply. Maybe one minor, as we now try to stick to the scheme of using square brackets, could you provide it as following: "[STREAMPIPES-336] XYZ" - that would be awesome.

**Comment by wipatrick** [comment]
Cheers @sndp2693 🎉

**Pull request merged**
