### PR TITLE
[STREAMPIPES-612] Add builder pattern for GenericAdapterStreamDescrip…

### PR DESCRIPTION
**Pull request by tenthe**
### Purpose
Until now, it was quite cumbersome to create a new AdapterDescription because we didn't provide a builder for that.

### Approach
Add a builder class `GenericDataStreamAdapterBuilder` to generate a new `GenericDataStreamAdapterDescription`

### Remarks

Related to [STREAMPIPES-612]

### CODE REVIEW

**Comment by tenthe** [comment]
@RobertIndie as discussed in #128 I added a builder to generate the adapter description.
However, I am not sure if this is already the best solution, because we have to 'recreate' the description that is already defined in the `declareModel` method of the adapter. 
Maybe we can find a way to only provide the user input programmatically for all the parameters.
What do you think?

**Review by RobertIndie — APPROVED** [review]

**Comment by RobertIndie** [comment]
> Maybe we can find a way to only provide the user input programmatically for all the parameters.

Sounds like a good idea. But I wonder what the `declareModel` method of adapters is used for currently.

**Comment by tenthe** [comment]
@RobertIndie yes, you are absolutely right. We have been quite inconsistent in the past. 
We have discussed this issue on the mailing list as well. 
I have enabled the checkstyle plugin for my IDE and tried to reformat the code before publishing it, but there might still be issues with my local configuration.
What is your opinion, should we include the code style changes gradually or should we automatically reformat the whole code base?
My idea was to gradually use a consistent code style to learn what is the best practice for the project. 
I'm happy to discuss this topic further, as I'm not sure how best to handle it with the existing code base.

**Comment by RobertIndie** [comment]
@tenthe I see that we already have the checkstyle convention here: https://github.com/apache/incubator-streampipes/blob/dev/tools/maven/checkstyle.xml If we are all still +1 for this convention, we can enforce the checkstyle for each module gradually. We may need to reformat the code in serval PRs. And these PRs should only care about the reformatting.

BTW, I'm +1 for merging this PR. We can still reformat these codes in another PR.

**Comment by tenthe** [comment]
@RobertIndie regarding the checkstyle, I do not have a strong opinion on which checkstyle configuration we use. I think it is important that we have a consistent code base. So I'm +1 for enforcing it gradually module by module.

**Pull request merged**
